name: Terraform Apply or Destroy Modules

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose whether to apply or destroy the infrastructure'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

env:
  aws_region: us-west-2
  image_tag: latest
  repo_name: eksdemo

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.aws_region }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply ECR Module
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          set -e
          terraform init
          terraform apply -target=module.ecr -auto-approve

      - name: Build, Tag and Push Docker Image
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          set -e
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          aws ecr get-login-password --region ${{ env.aws_region }} | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.${{ env.aws_region }}.amazonaws.com
          docker build -t ${{ env.repo_name }}:${{ env.image_tag }} ./flask-app
          docker tag ${{ env.repo_name }}:${{ env.image_tag }} $ACCOUNT_ID.dkr.ecr.${{ env.aws_region }}.amazonaws.com/${{ env.repo_name }}:${{ env.image_tag }}
          docker push $ACCOUNT_ID.dkr.ecr.${{ env.aws_region }}.amazonaws.com/${{ env.repo_name }}:${{ env.image_tag }}

      - name: Terraform Apply Remaining Modules
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          set -e
          if ! terraform apply -auto-approve; then
            echo "❌ Terraform apply failed. Destroying all modules in reverse order..."
            terraform destroy -target=module.helm -auto-approve || echo "Helm destroy failed"
            terraform destroy -target=module.eks -auto-approve || echo "EKS destroy failed"
            terraform destroy -target=module.vpc -auto-approve || echo "VPC destroy failed"
            terraform destroy -target=module.ecr -auto-approve || echo "ECR destroy failed"
            exit 1
          fi

      - name: Terraform Destroy All Modules
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          set -e
          echo "🛑 Destroying modules in reverse dependency order..."
          terraform destroy -target=module.helm -auto-approve || echo "Helm destroy failed"
          terraform destroy -target=module.eks -auto-approve || echo "EKS destroy failed"
          terraform destroy -target=module.vpc -auto-approve || echo "VPC destroy failed"
          terraform destroy -target=module.ecr -auto-approve || echo "ECR destroy failed"
          echo "✅ All specified modules destroyed"
