name: Terraform Apply or Destroy Modules

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose whether to apply or destroy the infrastructure'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

env:
  aws_region: us-west-2
  image_tag: latest
  repo_name: eksdemo

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.aws_region }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply ECR Module
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          terraform init
          terraform apply -target=module.ecr -auto-approve

      - name: Build, Tag and Push Docker Image
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          aws ecr get-login-password --region ${{ env.aws_region }} | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.${{ env.aws_region }}.amazonaws.com
          docker build -t ${{ env.repo_name }}:${{ env.image_tag }} ./flask-app
          docker tag eksdemo:latest $ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/eksdemo:latest
          docker push $ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/eksdemo:latest

      - name: Terraform Apply Remaining Modules
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          if terraform apply -auto-approve; then
            echo "✅ Terraform apply succeeded"
          else
            echo "❌ Terraform apply failed. Destroying all modules in reverse order..."

            # Delete orphaned ALB Security Groups first
            echo "🧹 Deleting orphaned ALB Security Groups..."
            for sg in $(aws ec2 describe-security-groups --filters Name=group-name,Values="*alb*" --query 'SecurityGroups[].GroupId' --output text); do
              echo "Deleting Security Group: $sg"
              aws ec2 delete-security-group --group-id $sg || echo "Failed to delete SG $sg"
            done

            terraform destroy -target=module.helm -auto-approve || echo "Helm destroy failed"
            terraform destroy -target=module.eks -auto-approve || echo "EKS destroy failed"
            terraform destroy -target=module.vpc -auto-approve || echo "VPC destroy failed"
            terraform destroy -target=module.ecr -auto-approve || echo "ECR destroy failed"
            exit 1
          fi

      - name: Verify Application Response
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          echo "🔎 Checking application response..."
          RESPONSE=$(curl -s https://www.saharbittman.com)
          if [ "$RESPONSE" = "Hello, World from Sahar Bittman!" ]; then
            echo "🎉 Pipeline succeeded: response matches expected output"
          else
            echo "⚠️ Response did not match expected output"
          fi

      - name: Terraform Destroy All Modules
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          # Delete orphaned ALB Security Groups first
          echo "🧹 Deleting orphaned ALB Security Groups..."
          for sg in $(aws ec2 describe-security-groups --filters Name=group-name,Values="*alb*" --query 'SecurityGroups[].GroupId' --output text); do
            echo "Deleting Security Group: $sg"
            aws ec2 delete-security-group --group-id $sg || echo "Failed to delete SG $sg"
          done

          echo "🛑 Destroying modules in reverse dependency order..."
          terraform destroy -target=module.helm -auto-approve || echo "Helm destroy failed"
          terraform destroy -target=module.eks -auto-approve || echo "EKS destroy failed"
          terraform destroy -target=module.vpc -auto-approve || echo "VPC destroy failed"
          terraform destroy -target=module.ecr -auto-approve || echo "ECR destroy failed"
          echo "✅ All specified modules destroyed"
